FROM microsoft/aspnetcore-build:2.1
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

WORKDIR /src
COPY Miniblog.Core.sln ./
COPY src/Miniblog.Core.csproj src/

RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/src
RUN dotnet build Miniblog.Core.csproj

CMD ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile"]